default:
  image: node:12.22.1

stages:
  - setup
  - build
  - test
  - coverage

install:
  stage: setup
  cache:
    key:
      files:
        - package-lock.json
      prefix: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
    policy: pull-push
  script:
    - npm ci
  only:
    - master
    - merge_requests

build:
  stage: build
  cache:
    key:
      files:
        - package-lock.json
      prefix: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
    policy: pull
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - master
    - merge_requests

lint:
  stage: test
  cache:
    key:
      files:
        - package-lock.json
      prefix: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
    policy: pull
  script:
    - npm run lint
  only:
    - master
    - merge_requests

test:
  stage: test
  cache:
    - key:
        files:
          - package-lock.json
        prefix: ${CI_COMMIT_REF_SLUG}
      paths:
        - node_modules
      policy: pull
    - key: ${CI_COMMIT_REF_SLUG}_coverage
      paths:
        - coverage/**/*
      policy: push
  script:
    - npm run test:ci
  only:
    - master
    - merge_requests

coverage:
  stage: coverage
  cache:
    - key:
        files:
          - package-lock.json
        prefix: ${CI_COMMIT_REF_SLUG}
      paths:
        - node_modules
      policy: pull
    - key: ${CI_COMMIT_REF_SLUG}_coverage
      paths:
        - coverage/**/*
      policy: pull
  script:
    - npm run test:report:coverage
  only:
    - master
    - merge_requests
